services:
  postgres:
    image: postgres:15-alpine
    container_name: store-multimarcas
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      LC_ALL: "pt_BR.UTF-8"
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "32768:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

    # Serviço do Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-ci
    user: "1000:984"  # ⚠️ IMPORTANTE: jenkins user : docker group
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS=-Duser.timezone=America/Sao_Paulo
    restart: unless-stopped

volumes:
  postgres_data:
  jenkins_data: